@extends('layouts.main') 
@section('title')
<title>About Us | DTU Times</title>
@endsection
@section('content') 
<!-- Page Title
		============================================= -->
		<section class="container-fluid img-responsive" id="page-title" style="padding: 0 0;">
        <img src="img/team2018.jpeg">
            

            
			

		</section>
            
        <section id="content">

			<div class="content-wrap">

				<div class="container clearfix">

				
                    <div class="row text-responsive" style="margin-top:5%">
                    
                    
					<div class="col-lg-6 col-md-6 col-sm-6">

						<div class="heading-block fancy-title nobottomborder title-bottom-border">
							<h4>Who we are</h4>
						</div>

						<p>DTU Times is the Official Newsletter of Delhi Technological University, formerly known as Delhi College of Engineering.
<br>
<br>
Founded as DCE Times in 2009 by Anand Meena and Abhishek Bindal, it was among the first college newspapers to be published across all engineering colleges in India. It has since transitioned into its current form as a Quarterly Newsletter, published with the aim of providing essential correspondence, news updates, and palatable articles to the students of the University. Our Online and Social Media presence includes a Facebook Page, an Instagram Handle, a Website, and a Blog on WordPress. 
<br>
<br>

We are team of over seventy Columnists, Designers, Photographers, Illustrators and Web Developers. Under the Patronage of Prof. Yogesh Singh, Hon’ble Vice-Chancellor, DTU, and the guidance of Sh. Anoop Lather, Public Relations Officer, DTU, Prof. S. Indu, HOD, Dept. of Electronics and Communication Engineering, DTU and Prof. Rajeshwari Pandey, Associate Dean - Academics (UG), DTU, DTU Times brings you the latest and the most correct information from the Administration, and a plethora of creative content for everyone’s reading pleasure. 
<br>
<br>

DTU Times is also chartered to chronicle the events and developments of DTU. A complete account of the reportage can be found in our past editions, accessible through this website in the ‘Editions’ section. With the aim of bringing the most timely notifications and engaging creative content, we the members of this team are at your service. 

                        </p>

					</div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        
                        <div class="heading-block fancy-title nobottomborder title-bottom-border">
							<h4>Editors' Message</h4>
						</div>

						<p>Back in 2009, DTU Times was started as an endeavour to bridge the gap between the administration and students of DTU (then DCE). Today, the team marks its presence on a multitude of portals, and apart from reporting news, is a content producer in its own merit. In this journey spanning nearly a decade, while DTU Times has evolved into a reliable media house with thousands of readers from DTU and beyond, the underlying philosophy of the team has remained unwavered.
 <br>
						<br>

We envisage DTU Times to be the one-stop destination for the Administration, Faculty, Alumni and Students of the University for all things DTU, be it News, Event Updates, or the products of the creative side of budding engineers. While fair reportage of events is what propels us, it forms a part of our duty to display to the world the multi-faceted personalities of the students of DTU. We also take pleasure in showcasing the creative content generated by our members, in the form of Blog Articles, Illustrations, or Photographs.
<br>

<br>We warmly welcome you to the revamped DTU Times Website. Explore the various sections, browse the blog or scan out the archive. You are sure to find content to suit your appetite, and more. There’s something in store for everyone!


                        </p>
					</div>
                        

                    </div>
				</div>

			</div>

		</section><!-- #content end -->


@endsection